#---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ProxyDefaults
#metadata:
#  name: global
#spec:
#  config:
#    protocol: http
#  meshGateway:
#    mode: local
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api
spec:
  protocol: http

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments
spec:
  protocol: http

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 18080
      protocol: http
      services:
        - name: api
          hosts: ["*"]

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
    - match:
        http:
          pathPrefix: /
      destination:
        service: api
        requestTimeout: 10s
        numRetries: 5
        retryOnConnectFailure: true
        retryOnStatusCodes:
          - 503


---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-gateway
spec:
  destination:
    name: ingress-gateway
  sources:
    - name: '*'
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
  sources:
    - name: ingress-gateway
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  destination:
    name: payments
  sources:
    - name: api
      action: allow
