---
apiVersion: v1
kind: Service
metadata:
  name: currency
  namespace: default
  labels:
    app: metrics
spec:
  selector:
    app: currency
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: metrics # prom scraping port
      protocol: TCP
      port: 20200
      targetPort: 20200

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency
  namespace: default
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  namespace: default
  labels:
    app: currency_v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
        metrics: enabled
    spec:
      serviceAccountName: currency
      automountServiceAccountToken: true
      containers:
        - name: currency
          image: nicholasjackson/fake-service:v0.23.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "Currency V1 Kubernetes"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:9090"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://tempo:9411"
            - name: "READY_CHECK_RESPONSE_DELAY"
              value: "10s"
          readinessProbe:
            httpGet:
              path: /ready
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
